### ISSUE TITLE
Error executing 'postInstallation': PHP Fatal error:  Uncaught Error: Wrong parameters for Elasticsearch

### ISSUE THREAD

**Issue by mfloriani** [bitnami/bitnami-docker-magento#121]
**Description**

I am getting the following error when I try to run Magento using the docker-composer file:
```
 Error executing 'postInstallation': PHP Fatal error:  Uncaught Error: Wrong parameters for Elasticsearch\Common\Exceptions\ServerErrorResponseException([string $message [, long $code [, Throwable $previous = NULL]]]) in /opt/bitnami/magento/htdocs/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:682
magento_1        | Stack trace:
magento_1        | #0 /opt/bitnami/magento/htdocs/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(682): Exception->__construct(NULL, 502)
magento_1        | #1 /opt/bitnami/magento/htdocs/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(298): Elasticsearch\Connections\Connection->process5xxError(Array, Array, Array)
magento_1        | #2 /opt/bitnami/magento/htdocs/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
magento_1        | #3 /opt/bitnami/magento/htdocs/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
magento_1        | #4 /opt/bitnami/magento/htdocs/vendor/guzzlehttp/ringphp/src/Co in /opt/bitnami/magento/htdocs/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 682
```
**Steps to reproduce the issue:**

1. curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-magento/master/docker-compose.yml > docker-compose.yml
2. docker-compose up -d

**Describe the results you received:**
```
Starting magento_elasticsearch_1 ... done
Starting magento_mariadb_1       ... done
Starting magento_magento_1       ... done
Attaching to magento_elasticsearch_1, magento_mariadb_1, magento_magento_1
mariadb_1        |  09:51:18.07
mariadb_1        |  09:51:18.07 Welcome to the Bitnami mariadb container
mariadb_1        |  09:51:18.08 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1        |  09:51:18.09 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1        |  09:51:18.10 Send us your feedback at containers@bitnami.com
mariadb_1        |  09:51:18.10
mariadb_1        |  09:51:18.11 INFO  ==> ** Starting MariaDB setup **
mariadb_1        |  09:51:18.25 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb_1        |  09:51:18.26 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1        |  09:51:18.27 INFO  ==> Initializing mariadb database
mariadb_1        |  09:51:18.31 INFO  ==> Using persisted data
mariadb_1        |  09:51:18.37 INFO  ==> Running mysql_upgrade
mariadb_1        |  09:51:18.38 INFO  ==> Starting mariadb in background
elasticsearch_1  |  09:51:16.77
elasticsearch_1  |  09:51:16.77 Welcome to the Bitnami elasticsearch container
elasticsearch_1  |  09:51:16.78 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
magento_1        |
magento_1        | Welcome to the Bitnami magento container
magento_1        | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-magento
magento_1        | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-magento/issues
magento_1        |
elasticsearch_1  |  09:51:16.78 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
elasticsearch_1  |  09:51:16.78 Send us your feedback at containers@bitnami.com
elasticsearch_1  |  09:51:16.79
elasticsearch_1  |  09:51:16.79 INFO  ==> ** Starting Elasticsearch setup **
elasticsearch_1  |  09:51:16.82 INFO  ==> Configuring/Initializing Elasticsearch...
elasticsearch_1  |  09:51:16.84 INFO  ==> Custom configuration file detected, using it...
elasticsearch_1  |  09:51:16.87 INFO  ==> ** Elasticsearch setup finished! **
elasticsearch_1  |
elasticsearch_1  |  09:51:16.88 INFO  ==> ** Starting Elasticsearch **
elasticsearch_1  | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
mariadb_1        |  09:51:21.09 INFO  ==> Stopping mariadb
mariadb_1        |  09:51:22.10 INFO  ==> ** MariaDB setup finished! **
mariadb_1        |
mariadb_1        |  09:51:22.20 INFO  ==> ** Starting MariaDB **
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.2.27-MariaDB) starting as process 1 ...
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] InnoDB: Uses event mutexes
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] InnoDB: Compressed tables use zlib 1.2.8
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] InnoDB: Using Linux native AIO
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] InnoDB: Number of pools: 1
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] InnoDB: Using SSE2 crc32 instructions
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1        | 2019-10-29  9:51:22 140014814840576 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] InnoDB: Highest supported file format is Barracuda.
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] InnoDB: 128 out of 128 rollback segments are active.
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] InnoDB: Waiting for purge to start
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] InnoDB: 5.7.27 started; log sequence number 12898975
mariadb_1        | 2019-10-29  9:51:22 140014574884608 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Warning] 'proxies_priv' entry '@% root@d9425e95f74b' ignored in --skip-name-resolve mode.
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] Reading of all Master_info entries succeeded
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] Added new Master_info '' to hash table
mariadb_1        | 2019-10-29  9:51:22 140015327434560 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_1        | Version: '10.2.27-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
mariadb_1        | 2019-10-29  9:51:22 140014574884608 [Note] InnoDB: Buffer pool(s) load completed at 191029  9:51:22
elasticsearch_1  | [2019-10-29T09:51:26,850][INFO ][o.e.e.NodeEnvironment    ] [697a06c50d00] using [1] data paths, mounts [[/bitnami/elasticsearch/data (/dev/sda1)]], net usable_space [24.2gb], net total_space [38.7gb], types [ext4]
elasticsearch_1  | [2019-10-29T09:51:26,940][INFO ][o.e.e.NodeEnvironment    ] [697a06c50d00] heap size [1007.3mb], compressed ordinary object pointers [true]
elasticsearch_1  | [2019-10-29T09:51:26,989][INFO ][o.e.n.Node               ] [697a06c50d00] node name [697a06c50d00], node ID [fogBi_w7Ss2KZe6J9dsJrw]
elasticsearch_1  | [2019-10-29T09:51:27,107][INFO ][o.e.n.Node               ] [697a06c50d00] version[6.8.4], pid[1], build[oss/tar/bca0c8d/2019-10-16T06:19:49.319352Z], OS[Linux/4.15.0-1044-gcp/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/11.0.5/11.0.5+10]
elasticsearch_1  | [2019-10-29T09:51:27,111][INFO ][o.e.n.Node               ] [697a06c50d00] JVM arguments [-Xms1024m, -Xmx1024m, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch-15333803269738610796, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -XX:UseAVX=2, -Des.path.home=/opt/bitnami/elasticsearch, -Des.path.conf=/opt/bitnami/elasticsearch/config, -Des.distribution.flavor=oss, -Des.distribution.type=tar]
elasticsearch_1  | [2019-10-29T09:51:30,701][INFO ][o.e.p.PluginsService     ] [697a06c50d00] loaded module [aggs-matrix-stats]
elasticsearch_1  | [2019-10-29T09:51:30,705][INFO ][o.e.p.PluginsService     ] [697a06c50d00] loaded module [analysis-common]
elasticsearch_1  | [2019-10-29T09:51:30,709][INFO ][o.e.p.PluginsService     ] [697a06c50d00] loaded module [ingest-common]
elasticsearch_1  | [2019-10-29T09:51:30,711][INFO ][o.e.p.PluginsService     ] [697a06c50d00] loaded module [ingest-geoip]
elasticsearch_1  | [2019-10-29T09:51:30,712][INFO ][o.e.p.PluginsService     ] [697a06c50d00] loaded module [ingest-user-agent]
elasticsearch_1  | [2019-10-29T09:51:30,720][INFO ][o.e.p.PluginsService     ] [697a06c50d00] loaded module [lang-expression]
elasticsearch_1  | [2019-10-29T09:51:30,721][INFO ][o.e.p.PluginsService     ] [697a06c50d00] loaded module [lang-mustache]
elasticsearch_1  | [2019-10-29T09:51:30,722][INFO ][o.e.p.PluginsService     ] [697a06c50d00] loaded module [lang-painless]
elasticsearch_1  | [2019-10-29T09:51:30,724][INFO ][o.e.p.PluginsService     ] [697a06c50d00] loaded module [mapper-extras]
elasticsearch_1  | [2019-10-29T09:51:30,725][INFO ][o.e.p.PluginsService     ] [697a06c50d00] loaded module [parent-join]
elasticsearch_1  | [2019-10-29T09:51:30,726][INFO ][o.e.p.PluginsService     ] [697a06c50d00] loaded module [percolator]
elasticsearch_1  | [2019-10-29T09:51:30,727][INFO ][o.e.p.PluginsService     ] [697a06c50d00] loaded module [rank-eval]
elasticsearch_1  | [2019-10-29T09:51:30,731][INFO ][o.e.p.PluginsService     ] [697a06c50d00] loaded module [reindex]
elasticsearch_1  | [2019-10-29T09:51:30,733][INFO ][o.e.p.PluginsService     ] [697a06c50d00] loaded module [repository-url]
elasticsearch_1  | [2019-10-29T09:51:30,734][INFO ][o.e.p.PluginsService     ] [697a06c50d00] loaded module [transport-netty4]
elasticsearch_1  | [2019-10-29T09:51:30,735][INFO ][o.e.p.PluginsService     ] [697a06c50d00] loaded module [tribe]
elasticsearch_1  | [2019-10-29T09:51:30,736][INFO ][o.e.p.PluginsService     ] [697a06c50d00] no plugins loaded
magento_1        | nami    INFO  Initializing magento
magento_1        | magento INFO  Preparing PHP environment...
magento_1        | magento INFO  Preparing webserver environment...
elasticsearch_1  | [2019-10-29T09:51:39,904][INFO ][o.e.d.DiscoveryModule    ] [697a06c50d00] using discovery type [single-node] and host providers [settings]
elasticsearch_1  | [2019-10-29T09:51:42,559][INFO ][o.e.n.Node               ] [697a06c50d00] initialized
elasticsearch_1  | [2019-10-29T09:51:42,561][INFO ][o.e.n.Node               ] [697a06c50d00] starting ...
elasticsearch_1  | [2019-10-29T09:51:43,385][INFO ][o.e.t.TransportService   ] [697a06c50d00] publish_address {172.19.0.2:9300}, bound_addresses {0.0.0.0:9300}
elasticsearch_1  | [2019-10-29T09:51:43,743][INFO ][o.e.h.n.Netty4HttpServerTransport] [697a06c50d00] publish_address {172.19.0.2:9200}, bound_addresses {0.0.0.0:9200}
elasticsearch_1  | [2019-10-29T09:51:43,744][INFO ][o.e.n.Node               ] [697a06c50d00] started
elasticsearch_1  | [2019-10-29T09:51:44,124][INFO ][o.e.g.GatewayService     ] [697a06c50d00] recovered [0] indices into cluster_state
magento_1        | magento INFO  Preparing Magento environment...
magento_1        | mysql-c INFO  Trying to connect to MySQL server
magento_1        | mysql-c INFO  Found MySQL server listening at mariadb:3306
magento_1        | mysql-c INFO  MySQL server listening and working at mariadb:3306
magento_1        | magento INFO  Installing Magento...
magento_1        | magento INFO  Deploying to developer mode...
magento_1        | magento INFO  Waiting for Elasticsearch at elasticsearch:9200
magento_1        | magento INFO  Configuring Elasticsearch...
magento_1        | magento INFO  Reindexing...
magento_1        | Error executing 'postInstallation': PHP Fatal error:  Uncaught Error: Wrong parameters for Elasticsearch\Common\Exceptions\ServerErrorResponseException([string $message [, long $code [, Throwable $previous = NULL]]]) in /opt/bitnami/magento/htdocs/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:682
magento_1        | Stack trace:
magento_1        | #0 /opt/bitnami/magento/htdocs/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(682): Exception->__construct(NULL, 502)
magento_1        | #1 /opt/bitnami/magento/htdocs/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(298): Elasticsearch\Connections\Connection->process5xxError(Array, Array, Array)
magento_1        | #2 /opt/bitnami/magento/htdocs/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
magento_1        | #3 /opt/bitnami/magento/htdocs/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
magento_1        | #4 /opt/bitnami/magento/htdocs/vendor/guzzlehttp/ringphp/src/Co in /opt/bitnami/magento/htdocs/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 682
magento_1        |
magento_magento_1 exited with code 1
```

**Describe the results you expected:**

I was expecting to have the containers up and running.

**Additional information you deem important (e.g. issue happens only occasionally):**

Well, first time I ran the docker-compose up I had to execute the following command to solve the problem **Elasticsearch requires at least: vm.max_map_count = 262144**

`sudo sysctl -w vm.max_map_count=262144`

**Version**

- Output of `docker version`:

```
Docker version 19.03.2, build 6a30dfc
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 8
  Running: 5
  Paused: 0
  Stopped: 3
 Images: 54
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-1044-gcp
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.298GiB
 Name: mfloria1-dev01
 ID: TEPN:ZOEN:IQDN:XPCL:CPZY:NLDQ:G2R4:WNAD:OH3N:TO5Q:TBUD:72BC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://10.255.0.83:80/
 HTTPS Proxy: http://10.255.0.83:80/
 No Proxy: localhost,127.0.0.1,.jlrint.com
 Username: mfloria1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.0, build 0aa59064
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

I am trying to run this Magento server in a VM instance on Google Cloud Platform behind a corporate proxy.

**Comment by jotamartos** [comment]
Hi @mfloriani,

Thank you for using Bitnami. We tried to reproduce the issue but we couldn't do so. We reviewed our daily tests and tested the solution locally but it worked as expected. We think that the container's information was not properly removed when you got the first error message (the one related to the memory). Can you try to remove all the data the containers created (using the down option with the -v parameter) and run the up command again?

```
docker-compose down -v
docker-compose up -d
```

Let us know if the solution works as expected now. 

Thanks,
Jota

**Comment by mfloriani** [comment]
Hi @jotamartos ,

I think it is something related to my environment.  
What I did was cloning another VM instance and installing in this new one and it is working.
It is weird because everything else is working properly in the other one.

Thanks anyway.
