### ISSUE TITLE
Installing Extensions Break Installation

### ISSUE THREAD

**Issue by mcclede** [bitnami/bitnami-docker-magento#212]
**Description**

Using the bitnami/magento container, I attempt to install an extension. This results in a failure that breaks the installation.
This is the first time I've tried to install extensions and I'm not sure that I'm doing it right. Particularly, I'm not sure what directory the extension should be installed from (see step 3 below).

**Steps to reproduce the issue:**

1. Use the attached docker-compose and CM_Initialize files to bring up the required containers
2. Install a Magento 2 extension. I've tried both MagePlaza magento 2 Banner Slider Extension and the Magento Magepal SMTP Extension (https://docs.bitnami.com/general/apps/magento/configuration/install-extension-smtp/)
3. Log into the bitnami/magento container
4. change directory to /bitnami/magento
5. composer require mageplaza/module-banner-slider
6. php bin/magento setup:upgrade
7. php bin/magento setup:static-content:deploy

**Describe the results you received:**

After completing step 7 above, I attempt to access the default page at http://localhost and get the following error in the log:

Uncaught ReflectionException: Class Magento\\Framework\\App\\ResourceConnection\\Proxy does not exist in /bitnami/magento/vendor/magento/framework/Code/Reader/ClassReader.php:28
 Stack trace:
 #0 /bitnami/magento/vendor/magento/framework/Code/Reader/ClassReader.php(28): ReflectionClass->__construct()
 #1 /bitnami/magento/vendor/magento/framework/ObjectManager/Definition/Runtime.php(54): Magento\\Framework\\Code\\Reader\\ClassReader->getConstructor()
 #2 /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(48): Magento\\Framework\\ObjectManager\\Definition\\Runtime->getParameters()
 #3 /bitnami/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create()
 #4 /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\\Framework\\ObjectManager\\ObjectManager->get()
 #5 /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\\Framework\\ObjectManage in /bitnami/magento/vendor/magento/framework/Code/Reader/ClassReader.php on line 28

**Describe the results you expected:**

I expected to get the default home page, and be able to access Magento Admin.

[docker-compose.txt](https://github.com/bitnami/bitnami-docker-magento/files/7289746/docker-compose.txt)

**Version**

- Output of `docker version`:
[CM_Initialize.txt](https://github.com/bitnami/bitnami-docker-magento/files/7289749/CM_Initialize.txt)

```
 PS D:\CM> docker version
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:58:50 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
 PS D:\CM> docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.3)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 25GiB
 Name: docker-desktop
 ID: SQ66:SYED:2U4B:FROC:SOXF:BQUP:LOVA:RXGZ:2WNY:UW2O:TLRQ:IS3U
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

- Output of `docker-compose version` (if applicable):

```
 PS D:\CM> docker compose version
Docker Compose version v2.0.0-rc.3
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Device name	ANGEL3
Processor	AMD Ryzen 5 5600X 6-Core Processor                3.70 GHz
Installed RAM	32.0 GB
Device ID	xxxxxxxxxxxxxxxxxxxxxxx
Product ID	00330-80000-00000-AA017
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Pro
Version	20H2
Installed on	‎5/‎5/‎2021
OS build	19042.1237
Experience	Windows Feature Experience Pack 120.2212.3530.0

**Comment by javsalgar** [comment]
Hi,

Note that you were following the instructions for the Single VM, which differ slightly from the container ones. Could you try repeating the commands in a fresh installation but executing first `su daemon -s /bin/bash`? That should avoid any permission issues.

**Comment by mcclede** [comment]
Sure. I'll give it a try. I'm totally new to GitHub.
