### ISSUE TITLE
Unable to properly install an extension on magento docker bitnami

### ISSUE THREAD

**Issue by jaaf85** [bitnami/bitnami-docker-magento#239]
### Name and Version

Bitnami-docker-magento

### What steps will reproduce the bug?

Hi,
I am trying to install an extension on Magento (Cloudinary - which is a top class provider). But after completing the installation process with the composer, I am faced with Class Not Found, 

I suspect some missing generated code: first I thought that it was related to my installation process with some permissions problem but I used the recommended steps on your readme page, with daemon user and I am facing this issue. 

BUG REPORT INFORMATION
here are key information from my environment:
--> Host OS: unbuntu 21.04
--> docker, docker-compose: version from June 2021
--> Magento community edition
--> extension to install: cloudinary-magento2 extension 

Description

**Access to Magento container bash from the host, using daemon user on Magento root directory:** 
```
sudo docker-compose exec magento bash
su daemon -s /bin/bash
cd /bitnami/magento
```
**Performing the installation process with daemon user when needed**
```
composer require cloudinary/cloudinary-magento2
php bin/magento maintenance:enable
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy -f
php bin/magento maintenance:disable
php bin/magento cache:flush
```

### What is the expected behavior?

access to the admin panel UI to configure the extension. and access to the store

### What do you see instead?

**on the admin panel:**

![image](https://user-images.githubusercontent.com/16804394/158533259-79778c05-140f-438f-b32e-89bf7b670621.png)

After clicking on settings to configure the cloudinary plugin I get  :
 ```
Error: Class 'Cloudinary\Cloudinary\Model\AutoUploadMapping\AutoUploadConfiguration' not found in /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121 Stack trace: #0 /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() #1 /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create() #2 /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get() #3 /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create() #4 
```

**on the store page :** 
```
1 exception(s):
Exception #0 (InvalidArgumentException): Plugin class Cloudinary\Cloudinary\Plugin\Cms\Block\Block doesn't exist

Exception #0 (InvalidArgumentException): Plugin class Cloudinary\Cloudinary\Plugin\Cms\Block\Block doesn't exist
<pre>#1 Magento\Framework\Interception\PluginList\PluginList->_inheritPlugins() called at [vendor/magento/framework/Interception/PluginList/PluginList.php:192]
#2 Magento\Framework\Interception\PluginList\PluginList->getNext() called at [generated/code/MGS/Mpanel/Block/Cms/Block/Interceptor.php:22]
#3 MGS\Mpanel\Block\Cms\Block\Interceptor->toHtml() called at [app/design/frontend/Mgs/claue/Magento_Theme/templates/html/header.phtml:23]
#4 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71]
#5 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/View/Element/Template.php:273]
#6 Magento\Framework\View\Element\Template->fetchView() called at [vendor/magento/framework/View/Element/Template.php:303]
#7 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1111]
#8 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1115]
#9 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:675]
#10 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:578]
#11 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:555]
#12 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#13 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#14 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#15 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#16 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#17 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#18 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#19 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#20 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#21 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#22 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#23 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
```

### Additional information

Additional information you deem important (e.g. issue happens only occasionally):
```
Version

Output of docker version:
Client: Docker Engine - Community
Version: 20.10.7
API version: 1.41
Go version: go1.13.15
Git commit: f0df350
Built: Wed Jun 2 12:00:45 2021
OS/Arch: linux/amd64
Context: default
Experimental: true
Server: Docker Engine - Community
Engine:
Version: 20.10.7
API version: 1.41 (minimum version 1.12)
Go version: go1.13.15
Git commit: b0f5bc3
Built: Wed Jun 2 11:58:56 2021
OS/Arch: linux/amd64
Experimental: false
containerd:
Version: 1.4.6
GitCommit: d71fcd7d8303cbf684402823e425e9dd2e99285d
runc:
Version: 1.0.0-rc95
GitCommit: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
docker-init:
Version: 0.19.0
GitCommit: de40ad0

Output of docker info:
Client:
Context: default
Debug Mode: false
Plugins:
app: Docker App (Docker Inc., v0.9.1-beta3)
buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
scan: Docker Scan (Docker Inc., v0.8.0)

Server:
Containers: 4
Running: 3
Paused: 0
Stopped: 1
Images: 4
Server Version: 20.10.7
Storage Driver: overlay2
Backing Filesystem: extfs
Supports d_type: true
Native Overlay Diff: true
userxattr: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Cgroup Version: 1
Plugins:
Volume: local
Network: bridge host ipvlan macvlan null overlay
Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
init version: de40ad0
Security Options:
apparmor
seccomp
Profile: default
Kernel Version: 5.11.0-17-generic
Operating System: Ubuntu 21.04
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.581GiB
Name: vps-73c654a3
ID: 7ISF:DTCZ:LYLM:22LP:EGZK:AKCJ:5EUB:GXEF:DH37:TPWS:GDP2:44N6
Docker Root Dir: /var/lib/docker
Debug Mode: false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false
```

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-magento#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by hussam-qasem** [comment]
Would it be possible that this problem is related to the extension itself? Did you confirm that the extension version is compatible with your version of Magento?

**Comment by jaaf85** [comment]
Hi hussam-quasem, 

Thank you for your reply. 
the extension is compatible with my magento version CE 2.4 . 

Always when there is a bug , you have to suspect all the parties involved :-) So yes it might be a bug on their part . But right now, regarding the issue, I suspect more a permission or link issue on the bitnami stack, when I do the setup upgrade or setup:di:compile on the bitnami stack , while the missing classes exists in the bitnami/magento/vendor/ cloudinary  directory after composer require command.
But do not exists on the generated code .

Also for information cloudinary is a leading DAM provider on the market with active user on it and magento . So it is normally a well crafted extension. So,  I am more suspecting my « user error » or some tricky permission thing related to the hardened bitnami stack . 

Thanks
