### ISSUE TITLE
Bitnami Magento installation script unnecessarily uses grant ALL PRIVILEGES when creating the MySQL database

### ISSUE THREAD

**Issue by sabbour** [bitnami/bitnami-docker-magento#72]
During the Magento postInstallation steps, the script is calling grantPrivileges without actually specifying which privileges to set, which defaults to ALL.

There are several issues here:

- This is not secure.
- This is not actually required as the required privileges that Magento2 checks are listed here: https://github.com/magento/magento2/issues/5410.
- This fails on environments where the database user the script is using doesn't necessarily have privileges to grant ALL PRIVILEGES. For example, using the Open Service Broker for Azure on Kubernetes (see: https://github.com/Azure/open-service-broker-azure/issues/197).

I'm not sure if the source for this script is on GitHub somewhere?

Offending line in ``/root/.nami/components/com.bitnami.magento/lib/handlers/databases/mysql/index.js`` line 92:

```
mysqlCore.grantPrivileges(
      databaseSettings.name,
      databaseSettings.user,
      _.extend(options, this.connection, {databaseUserPassword: databaseSettings.password})
    );
```

Failing installation:
```
mysql-c TRACE [execute] Executing: mysql -N -P 3306 -h[redacted] -u[redacted] -p[redacted] -e GRANT ALL ON `bitnami_magento`.* TO 'bn_magento'@'%' IDENTIFIED BY '[redacted]'
mysql-c TRACE [execute] Result: {"code":1,"stdout":"","stderr":"ERROR 1044 (42000) at line 1: Access denied for user '[redacted]'@'%' to database 'bitnami_magento'\n"}

Error executing 'postInstallation': MySQL command failed to run. Error: 
 ERROR 1044 (42000) at line 1: Access denied for user '[redacted]'@'%' to database 'bitnami_magento'

     at execute (/root/.nami/components/com.bitnami.mysql-client/lib/databases/mysql/index.js:77:13)
    at _.forEach (/root/.nami/components/com.bitnami.mysql-client/lib/databases/mysql/index.js:495:7)
    at ot (/opt/bitnami/nami/node_modules/lodash/index.js:12:507)
    at Function.&lt;anonymous&gt; (/opt/bitnami/nami/node_modules/lodash/index.js:33:421)
    at Function.&lt;anonymous&gt; (/opt/bitnami/nami/node_modules/lodash/index.js:33:285)
    at Object.grantPrivileges (/root/.nami/components/com.bitnami.mysql-client/lib/databases/mysql/index.js:491:7)
    at Object.&lt;anonymous&gt; (/opt/bitnami/nami/node_modules/lodash/index.js:33:285)
    at MysqlHandler.createDatabaseForApp (/root/.nami/components/com.bitnami.magento/lib/handlers/databases/mysql/index.js:92:15)
    at Component.$app.postInstallation (/root/.nami/components/com.bitnami.magento/main.js:70:21)
    at Component.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
```

**Comment by beltran-rubo** [comment]
Hi,

Thanks for reporting it and for adding so many details. Unfortunately we do not have the code of all the modules available in a repo but the code is available from the tarball as you posted in this comment.

In this specific case we think the best solution is to add support for Magento to use an existing database (as you proposed in #73), that way you can configure the privileges of the database and the application does not require root privileges. We are working on it to support this scenario (similar to other applications like https://github.com/bitnami/bitnami-docker-wordpress or https://github.com/bitnami/bitnami-docker-mediawiki).
