### ISSUE TITLE
After intalling: ReflectionException): Class Magento\ConfigurableProduct\Model\Product\Cache\Tag\Configurable does not exist

### ISSUE THREAD

**Issue by pietrobr** [bitnami/bitnami-docker-magento#88]
After istalling using docker-compose up -d and navigating to my local url (localhost:89) I get this error
I've tryed different images for Magneto (2.2.4, 2.2.5), but same behaviour

(I'm using Windows 10, Docker 18.06.0-ce-win69 (19070))

```
1 exception(s):
Exception #0 (ReflectionException): Class Magento\ConfigurableProduct\Model\Product\Cache\Tag\Configurable does not exist

Exception #0 (ReflectionException): Class Magento\ConfigurableProduct\Model\Product\Cache\Tag\Configurable does not exist
#0 /opt/bitnami/magento/htdocs/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\Configu...')
#1 /opt/bitnami/magento/htdocs/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Configu...')
#2 /opt/bitnami/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(48): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Configu...')
#3 /opt/bitnami/magento/htdocs/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Configu...')
#4 /opt/bitnami/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(180): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Configu...')
#5 /opt/bitnami/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(156): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray(Array)
#6 /opt/bitnami/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, NULL, Array, 'customStrategie...', 'Magento\\Framewo...')
#7 /opt/bitnami/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Framewo...', Array, Array)
#8 /opt/bitnami/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#9 /opt/bitnami/magento/htdocs/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#10 /opt/bitnami/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#11 /opt/bitnami/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'factory', 'Magento\\Framewo...')
#12 /opt/bitnami/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Framewo...', Array, Array)
#13 /opt/bitnami/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#14 /opt/bitnami/magento/htdocs/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#15 /opt/bitnami/magento/htdocs/vendor/magento/module-page-cache/Observer/FlushCacheByTags.php(94): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#16 /opt/bitnami/magento/htdocs/vendor/magento/module-page-cache/Observer/FlushCacheByTags.php(64): Magento\PageCache\Observer\FlushCacheByTags->getTagResolver()
#17 /opt/bitnami/magento/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Magento\PageCache\Observer\FlushCacheByTags->execute(Object(Magento\Framework\Event\Observer))
#18 /opt/bitnami/magento/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\PageCache\Observer\FlushCacheByTags), Object(Magento\Framework\Event\Observer))
#19 /opt/bitnami/magento/htdocs/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#20 /opt/bitnami/magento/htdocs/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('clean_cache_by_...', Array)
#21 /opt/bitnami/magento/htdocs/vendor/magento/framework/Model/AbstractModel.php(817): Magento\Framework\Event\Manager\Proxy->dispatch('clean_cache_by_...', Array)
#22 /opt/bitnami/magento/htdocs/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(832): Magento\Framework\Model\AbstractModel->afterSave()
#23 /opt/bitnami/magento/htdocs/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(418): Magento\Framework\Model\ResourceModel\Db\AbstractDb->processAfterSaves(Object(Magento\Customer\Model\Visitor))
#24 /opt/bitnami/magento/htdocs/generated/code/Magento/Customer/Model/ResourceModel/Visitor/Interceptor.php(102): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Magento\Customer\Model\Visitor))
#25 /opt/bitnami/magento/htdocs/vendor/magento/framework/Model/AbstractModel.php(647): Magento\Customer\Model\ResourceModel\Visitor\Interceptor->save(Object(Magento\Customer\Model\Visitor))
#26 /opt/bitnami/magento/htdocs/vendor/magento/module-customer/Model/Visitor.php(163): Magento\Framework\Model\AbstractModel->save()
#27 /opt/bitnami/magento/htdocs/vendor/magento/module-customer/Observer/Visitor/InitByRequestObserver.php(24): Magento\Customer\Model\Visitor->initByRequest(Object(Magento\Framework\Event\Observer))
#28 /opt/bitnami/magento/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Magento\Customer\Observer\Visitor\InitByRequestObserver->execute(Object(Magento\Framework\Event\Observer))
#29 /opt/bitnami/magento/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Customer\Observer\Visitor\InitByRequestObserver), Object(Magento\Framework\Event\Observer))
#30 /opt/bitnami/magento/htdocs/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#31 /opt/bitnami/magento/htdocs/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('controller_acti...', Array)
#32 /opt/bitnami/magento/htdocs/vendor/magento/framework/App/Action/Action.php(96): Magento\Framework\Event\Manager\Proxy->dispatch('controller_acti...', Array)
#33 /opt/bitnami/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#34 /opt/bitnami/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Cms\Controller\Index\Index\Interceptor->___callParent('dispatch', Array)
#35 /opt/bitnami/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cms\Controller\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#36 /opt/bitnami/magento/htdocs/generated/code/Magento/Cms/Controller/Index/Index/Interceptor.php(39): Magento\Cms\Controller\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#37 /opt/bitnami/magento/htdocs/vendor/magento/framework/App/FrontController.php(55): Magento\Cms\Controller\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#38 /opt/bitnami/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#39 /opt/bitnami/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#40 /opt/bitnami/magento/htdocs/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#41 /opt/bitnami/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#42 /opt/bitnami/magento/htdocs/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#43 /opt/bitnami/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#44 /opt/bitnami/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#45 /opt/bitnami/magento/htdocs/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#46 /opt/bitnami/magento/htdocs/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#47 /opt/bitnami/magento/htdocs/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#48 /opt/bitnami/magento/htdocs/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#49 /opt/bitnami/magento/htdocs/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#50 {main}
```

**Comment by tompizmor** [comment]
Hello @pietrobr,

Would you mind sharing the docker-compose file that you are using? I cannot reproduce the issue using this [docker-compose](https://github.com/bitnami/bitnami-docker-magento/blob/master/2/debian-9/docker-compose.yml) from the repository.

**Comment by pietrobr** [comment]
Hi Tomas, I used the one from https://raw.githubusercontent.com/bitnami/bitnami-docker-magento/master/docker-compose.yml

I get the same errors also from Ubunto e Debian. I solved giving some permission on this folder /opt/bitnami as a quick fix.

**Comment by tompizmor** [comment]
hhhm....🤔

I don't see how giving permissions to `/opt/bitnami` fixed the issue. There is not any permission error in the logs that you have shared.

You said that you accessed to `http//:localhost:89` so at least you have to change the port maping in the docker-compose file. Did you also change something related with the volumes? Maybe you are using a local volume?

**Comment by pietrobr** [comment]
I tried to install also today in Kubernets unsing Helm (helm install stable/magento) and even here I get some permission errors (not show above, but in apache error log file). 
Today the error was similar to this (… page_cache" is not writable ...) , but with different directory, because I'm using the bitnami image): https://magento.stackexchange.com/questions/156421/php-fatal-error-uncaught-zend-cache-exception.

Doing from magento container in a pod: cat /opt/bitnami/apache/logs/error_log

[Fri Jul 27 15:35:30.212291 2018] [:error] [pid 119] [client 10.244.1.1:58004] PHP Fatal error:  Uncaught Zend_Cache_Exception: cache_dir "/opt/bitnami/magento/htdocs/var/page_cache" is not writable in /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php:209\nStack trace:\n#0 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache/Backend/File.php(180): Zend_Cache::throwException('cache_dir "/opt...')\n#1 /opt/bitnami/magento/htdocs/vendor/colinmollenhour/cache-backend-file/File.php(87): Zend_Cache_Backend_File->setCacheDir('/opt/bitnami/ma...')\n#2 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_File->__construct(Array)\n#3 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true)\n#4 /opt/bitnami/magento/htdocs/vendor/magento/framework/App/Cache/Frontend/Factory.php(158): Zend_Cache::factory('Magento\\\\Framewo...', 'Cm_Cache_Backen...', Array, Array, true, true, true)\n#5 /opt/bitnami/magento/htdocs/vendor/magento/ in /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php on line 209
root@intended-coral-magento-5dbdcffd59-mk7pc:/#

**Comment by tompizmor** [comment]
- For the docker-compose issues:

Could you let me know your host OS version? Debian, Centos, Suse,...?
In the past I found some issues on Centos systems because of SELinux didn't allow the image to configure the permissions.

- For the kubernetes issue:

Which distribution are you trying the helm chart in? Minikube, GKE, AKS, EKS, ...?

**Comment by pietrobr** [comment]
For docker-copose was a VM on Azure with Debian 9
For Kubernetes was Azure Kubernetes Services (AKS)

**Comment by tompizmor** [comment]
@pietrobr I am trying to test the latest version of the Magento chart in AKS but I am finding different issues. I will continue tomorrow and let you know if I found anything.

**Comment by tompizmor** [comment]
All I get in AKS at this moment is the next issue:

```
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at magento-mariadb:3306
mysql-c ERROR [canConnect] Connection with 'bn_magento' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'bn_magento' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'bn_magento' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'bn_magento' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'bn_magento' user is unsuccessful
Error executing 'postInstallation': Cannot connect to MySQL server:
```

It is very weird because I cannot reproduce it for example in Minikube...

**Comment by tompizmor** [comment]
@pietrobr I just could deploy the Magento helm chart successfully on AKS. 

I deployed the latest version of the chart (`magento-2.0.3`) as yesterday I updated the MariaDB dependency.

The deployment was quite slow but at the end I could access to Magento. 

Could you try again with the latest version of the chart? Also, my kubernetes version is 1.9.9.
