### ISSUE TITLE
Not working as expected. No app running

### ISSUE THREAD

**Issue by travis5491811** [bitnami/bitnami-docker-magento#90]
**Not working as expected, app not available at ip address**

I am just trying to get magento running using the instructions from this site. Everything appears to be working as normal while doing the setup. If i run `docker-compose up -d` it started building the app. I visited the ip of my machine (that only has this project on it....fresh install of ubuntu 16.04 LTS) and at first the url had a bitnami logo and text saying the application was installing. Then nothing.

`docker ps -a` shows that bitnami/magento:latest and bitnami/mariadb:latest both have a status of Up.

**Steps to reproduce the issue:**

1. Fresh install of Ubuntu 16.04 LTS, run all updates
2. Perform docker pre-install and installation steps.
3. Run the following 2 commands
```
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-magento/master/docker-compose.yml > docker-compose.yml   
$ docker-compose up -d
```
4. Visit ip address of machine and there is no app running 

**Describe the results you received:**

No app available in browser. If i curl from the local machine i get the following:

```
 curl -v localhost
* Rebuilt URL to: localhost/
*   Trying ::1...
* Connected to localhost (::1) port 80 (#0)
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Date: Thu, 16 Aug 2018 16:03:57 GMT
< Server: Apache/2.4.34 (Unix) OpenSSL/1.1.0f PHP/7.0.31
< X-Powered-By: PHP/7.0.31
< Set-Cookie: store=default; expires=Fri, 16-Aug-2019 16:03:57 GMT; Max-Age=31536000; path=/index.php/; HttpOnly
< Set-Cookie: PHPSESSID=7o1p54l4ucluop0jd8kcg360o4; expires=Thu, 16-Aug-2018 17:03:57 GMT; Max-Age=3600; path=/; domain=localhost; HttpOnly
< Expires: Wed, 16 Aug 2017 16:03:57 GMT
< Cache-Control: max-age=0, must-revalidate, no-cache, no-store
< Pragma: no-cache
< Location: http://127.0.0.1/index.php/?SID=7o1p54l4ucluop0jd8kcg360o4
< X-Magento-Cache-Control: max-age=0, must-revalidate, no-cache, no-store
< X-Magento-Cache-Debug: MISS
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: SAMEORIGIN
< X-UA-Compatible: IE=edge
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
< 
* Connection #0 to host localhost left intact
```

**Describe the results you expected:**

A magento app

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:09:05 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

- Output of `docker info`:

```
Containers: 7
 Running: 2
 Paused: 0
 Stopped: 5
Images: 3
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-133-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953GiB
Name: magentodev
ID: FML2:GGOA:MOJQ:SAFJ:MANI:TZDU:P5PD:HONH:XMCI:6M64:WNHI:7URF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Running in VMWare ESXi. I realize i can import vm image. I'm just trying to see why the docker method is not working as expected...or what important steps are missing from docs that would be helpful for someone who is not a docker expert and just trying to get a demo app running.

**Comment by juan131** [comment]
> at first the url had a bitnami logo and text saying the application was installing. Then nothing.

Magento take some time in order to be initialised. However, after a while you should be able to access Magento.

Could you please share the output of running the command below?

```
docker-compose logs magento
```

**Comment by zhukovra** [comment]
Agree with @juan131. Just wait in docker-compose logs that:
```
magento_1  | nami    INFO  magento successfully initialized
```
And after that all should works.

**Comment by travis5491811** [comment]
`$ docker-compose logs magento`


```
Attaching to travis_magento_1
magento_1  | 
magento_1  | Welcome to the Bitnami magento container
magento_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-magento
magento_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-magento/issues
magento_1  | 
magento_1  | nami    INFO  Initializing apache
magento_1  | apache  INFO  ==> Patching httpoxy...
magento_1  | nami    INFO  apache successfully initialized
magento_1  | nami    INFO  Initializing php
magento_1  | nami    INFO  php successfully initialized
magento_1  | nami    INFO  Initializing mysql-client
magento_1  | nami    INFO  mysql-client successfully initialized
magento_1  | nami    INFO  Initializing magento
magento_1  | magento INFO  Preparing PHP environment...
magento_1  | magento INFO  Preparing webserver environment...
magento_1  | magento INFO  Preparing Magento environment...
magento_1  | mysql-c INFO  Trying to connect to MySQL server
magento_1  | mysql-c INFO  Found MySQL server listening at mariadb:3306
magento_1  | mysql-c INFO  MySQL server listening and working at mariadb:3306
magento_1  | magento INFO  Installing Magento...
magento_1  | magento INFO  Deploying to developer mode...
magento_1  | magento INFO  Reindexing...
magento_1  | magento INFO  Flushing cache...
magento_1  | magento INFO  Cleaning up cache folders after installing
magento_1  | magento INFO 
magento_1  | magento INFO  ########################################################################
magento_1  | magento INFO   Installation parameters for magento:
magento_1  | magento INFO     Username: user
magento_1  | magento INFO     Site URL: http://127.0.0.1/
magento_1  | magento INFO     Admin URL: http://127.0.0.1/admin
magento_1  | magento INFO   This installation requires no credentials.
magento_1  | magento INFO  ########################################################################
magento_1  | magento INFO 
magento_1  | nami    INFO  magento successfully initialized
magento_1  | INFO  ==> Starting magento... 
magento_1  | 192.168.0.209 - - [16/Aug/2018:15:31:49 +0000] "GET / HTTP/1.1" 503 3746
magento_1  | 192.168.0.209 - - [16/Aug/2018:15:31:49 +0000] "GET /img/white_bitnami.png HTTP/1.1" 200 6931
magento_1  | 192.168.0.209 - - [16/Aug/2018:15:31:49 +0000] "GET /favicon.ico HTTP/1.1" 404 3746
magento_1  | 192.168.0.209 - - [16/Aug/2018:15:32:09 +0000] "GET / HTTP/1.1" 503 3746
magento_1  | 192.168.0.209 - - [16/Aug/2018:15:32:09 +0000] "GET /img/white_bitnami.png HTTP/1.1" 304 -
magento_1  | 192.168.0.209 - - [16/Aug/2018:15:32:29 +0000] "GET / HTTP/1.1" 500 -
magento_1  | 192.168.0.209 - - [16/Aug/2018:15:32:41 +0000] "GET / HTTP/1.1" 500 -
magento_1  | 192.168.0.209 - - [16/Aug/2018:15:32:42 +0000] "GET / HTTP/1.1" 500 -
magento_1  | 192.168.0.209 - - [16/Aug/2018:15:33:07 +0000] "GET / HTTP/1.1" 500 -
magento_1  | 192.168.0.209 - - [16/Aug/2018:15:33:30 +0000] "GET / HTTP/1.1" 500 -
```

I'm not sure why the 404 and 503 errors. That is the correct ip address of the machine. I didn't see any config steps where I was suppose to do anything with the ip. Any ideas?

**Comment by juan131** [comment]
Hi @travis5491811 

Let's take a look to the Apache error log so we can obtain more information about the reason why you're obtaining those 500 errors. Could you run the commands below and share the output?

```
docker-compose exec magento cat /opt/bitnami/apache/logs/error_log
```

**Comment by travis5491811** [comment]
@juan131 

```
$ docker-compose exec magento cat /opt/bitnami/apache/logs/error_log
ERROR: No container found for magento_1
```

**Comment by juan131** [comment]
Hi @travis5491811 

It seme there were some errors with the cache because of a permission issue:

```
[Thu Aug 16 15:32:29.332397 2018] [:error] [pid 134] [client 192.168.0.209:60498] PHP Fatal error:  Uncaught Zend_Cache_Exception: cache_dir "/opt/bitnami/magento/htdocs/var/page_cache" is not writable in /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php:209\nStack trace:\n#0 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache/Backend/File.php(180): Zend_Cache::throwException('cache_dir "/opt...')\n#1 /opt/bitnami/magento/htdocs/vendor/colinmollenhour/cache-backend-file/File.php(87): Zend_Cache_Backend_File->setCacheDir('/opt/bitnami/ma...')\n#2 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_File->__construct(Array)\n#3 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true)\n#4 /opt/bitnami/magento/htdocs/vendor/magento/framework/App/Cache/Frontend/Factory.php(157): Zend_Cache::factory('Magento\\\\Framewo...', 'Cm_Cache_Backen...', Array, Array, true, true, true)\n#5 /opt/bitnami/magento/htdocs/vendor/magento/ in /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php on line 209, referer: http://192.168.0.252/
[Thu Aug 16 15:32:41.797472 2018] [:error] [pid 135] [client 192.168.0.209:60500] PHP Fatal error:  Uncaught Zend_Cache_Exception: cache_dir "/opt/bitnami/magento/htdocs/var/page_cache" is not writable in /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php:209\nStack trace:\n#0 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache/Backend/File.php(180): Zend_Cache::throwException('cache_dir "/opt...')\n#1 /opt/bitnami/magento/htdocs/vendor/colinmollenhour/cache-backend-file/File.php(87): Zend_Cache_Backend_File->setCacheDir('/opt/bitnami/ma...')\n#2 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_File->__construct(Array)\n#3 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true)\n#4 /opt/bitnami/magento/htdocs/vendor/magento/framework/App/Cache/Frontend/Factory.php(157): Zend_Cache::factory('Magento\\\\Framewo...', 'Cm_Cache_Backen...', Array, Array, true, true, true)\n#5 /opt/bitnami/magento/htdocs/vendor/magento/ in /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php on line 209
[Thu Aug 16 15:32:42.978246 2018] [:error] [pid 136] [client 192.168.0.209:60502] PHP Fatal error:  Uncaught Zend_Cache_Exception: cache_dir "/opt/bitnami/magento/htdocs/var/page_cache" is not writable in /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php:209\nStack trace:\n#0 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache/Backend/File.php(180): Zend_Cache::throwException('cache_dir "/opt...')\n#1 /opt/bitnami/magento/htdocs/vendor/colinmollenhour/cache-backend-file/File.php(87): Zend_Cache_Backend_File->setCacheDir('/opt/bitnami/ma...')\n#2 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_File->__construct(Array)\n#3 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true)\n#4 /opt/bitnami/magento/htdocs/vendor/magento/framework/App/Cache/Frontend/Factory.php(157): Zend_Cache::factory('Magento\\\\Framewo...', 'Cm_Cache_Backen...', Array, Array, true, true, true)\n#5 /opt/bitnami/magento/htdocs/vendor/magento/ in /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php on line 209
[Thu Aug 16 15:33:07.455057 2018] [:error] [pid 137] [client 192.168.0.209:60518] PHP Fatal error:  Uncaught Zend_Cache_Exception: cache_dir "/opt/bitnami/magento/htdocs/var/page_cache" is not writable in /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php:209\nStack trace:\n#0 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache/Backend/File.php(180): Zend_Cache::throwException('cache_dir "/opt...')\n#1 /opt/bitnami/magento/htdocs/vendor/colinmollenhour/cache-backend-file/File.php(87): Zend_Cache_Backend_File->setCacheDir('/opt/bitnami/ma...')\n#2 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_File->__construct(Array)\n#3 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true)\n#4 /opt/bitnami/magento/htdocs/vendor/magento/framework/App/Cache/Frontend/Factory.php(157): Zend_Cache::factory('Magento\\\\Framewo...', 'Cm_Cache_Backen...', Array, Array, true, true, true)\n#5 /opt/bitnami/magento/htdocs/vendor/magento/ in /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php on line 209
[Thu Aug 16 15:33:30.065899 2018] [:error] [pid 138] [client 192.168.0.209:60520] PHP Fatal error:  Uncaught Zend_Cache_Exception: cache_dir "/opt/bitnami/magento/htdocs/var/page_cache" is not writable in /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php:209\nStack trace:\n#0 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache/Backend/File.php(180): Zend_Cache::throwException('cache_dir "/opt...')\n#1 /opt/bitnami/magento/htdocs/vendor/colinmollenhour/cache-backend-file/File.php(87): Zend_Cache_Backend_File->setCacheDir('/opt/bitnami/ma...')\n#2 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_File->__construct(Array)\n#3 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true)\n#4 /opt/bitnami/magento/htdocs/vendor/magento/framework/App/Cache/Frontend/Factory.php(157): Zend_Cache::factory('Magento\\\\Framewo...', 'Cm_Cache_Backen...', Array, Array, true, true, true)\n#5 /opt/bitnami/magento/htdocs/vendor/magento/ in /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php on line 209
[Tue Aug 21 15:14:03.354105 2018] [ssl:warn] [pid 64] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Tue Aug 21 15:14:03.354724 2018] [ssl:warn] [pid 64] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Tue Aug 21 15:14:03.390416 2018] [so:warn] [pid 64] AH01574: module rewrite_module is already loaded, skipping
```

However, I'm unable to reproduce the issue.. Indeed, the directory it's complaining about has writing permissions for the user **daemon** (the one that runs Apache):

```
docker-compose exec magento ls -la  /opt/bitnami/magento/htdocs/var/page_cache
total 8
drwxrwsr-x 2 bitnami daemon 4096 Aug 22 07:07 .
drwxrwsr-x 7 bitnami daemon 4096 Aug 22 07:14 ..
```

Could you run the previous command and share the output?

**Comment by travis5491811** [comment]
Hey @juan131 

$ docker-compose exec magento ls -la  /opt/bitnami/magento/htdocs/var/page_cach
ls: cannot access '/opt/bitnami/magento/htdocs/var/page_cach': No such file or directory

**Comment by travis5491811** [comment]
Hey @juan131, sorry about that.

```
$ docker-compose exec magento ls -la  /opt/bitnami/magento/htdocs/var/page_cache
total 12
drwxrwsr-x 3 bitnami daemon 4096 Aug 22 08:01 .
drwxrwsr-x 7 bitnami daemon 4096 Aug 22 14:50 ..
drwxrwsr-x 2 bitnami daemon 4096 Aug 22 08:01 mage-tags
```

**Comment by juan131** [comment]
Hi @travis5491811 

As you can check the permissions seem to be fine there... The user **daemon** has writing permissions on that cache directory... 

On a previous message you mentioned:

>  had to run docker compose up first.

Did Magento started smoothly after running `docker-compose up`? Can you access through a browser to it?

**Comment by travis5491811** [comment]
Hey @juan131,
I did not get any errors when i ran docker compose up but still cant access via browser or local terminal. One thing that is strange is when i try to access via browser on another computer, it redirects to local host:

`http://127.0.0.1/index.php/?SID=4hmofqs38hu7pnmfg3a2a8q5q4`

**Comment by juan131** [comment]
Hi @travis5491811 

As it's mentioned on the REAMDE.md, it's necessary to configure Magento Hostname to avoid being redirected to localhost:

> Note: If you want to access your application from a public IP or hostname you need to configure the application domain. You can handle it adjusting the configuration of the instance by setting the environment variable "MAGENTO_HOST" to your public IP or hostname.

**Comment by travis5491811** [comment]
Hey @juan131, 
Here is that part of my docker-compose.yml. I did forget to add it before but even after adding it and rebooting the host, the result is the same.
```
    environment:
      - MAGENTO_HOST=192.168.0.252
```

**Comment by juan131** [comment]
Hi @travis5491811,

 Did you add that configuration to the `docker-compose.yaml` after you had created the containers? Please not that this env. variable is only considered on the first boot.

**Comment by travis5491811** [comment]
@juan131, thanks. good to know. I shutdown running container (`docker ps -a` showed nothing running) and then made sure all containers were removed with `docker system prune -a`. This system is only used for testing this docker. 

After that, I ran `docker-compose up -d` and it went through downloading the image and initialization. The following .yml was in place when i ran that command:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_PASSWORD=magento_db_password
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami'
  magento:
    image: 'bitnami/magento:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      - MAGENTO_HOST=192.168.0.252
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento_db_password
      - MAGENTO_DATABASE_NAME=bitnami_magento
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'magento_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
```
It works on local (tested with `wget`). But going to 192.168.0.252 still redirects to `http://127.0.0.1/index.php/?SID=262f4dqftpff0edkd6qbatd5e4` so when i try to access from another computer, the same thing happens.

**Comment by juan131** [comment]
Hi @travis5491811 

Did you clean up your volumes before running `docker-compose up`? I was unable to reproduce the issue...

Just to give more context... When you setup that env. variable Magento is installed with the following parameters (within others):

```
--base-url http://${MAGENTO_HOST}/
--base-url-secure  https://${MAGENTO_HOST}/
```

You should obtain the following output once Magento is started (using **my.magento.site** on this example):

```
$ docker-compose logs magento
...
magento_1  | magento INFO  ########################################################################
magento_1  | magento INFO   Installation parameters for magento:
magento_1  | magento INFO     Username: user
magento_1  | magento INFO     Site URL: http://my.magento.site/
magento_1  | magento INFO     Admin URL: http://my.magento.site/admin
magento_1  | magento INFO   This installation requires no credentials.
magento_1  | magento INFO  ########################################################################
magento_1  | magento INFO
magento_1  | nami    INFO  magento successfully initialized
magento_1  | INFO  ==> Starting magento...
```

However, if there's data on the volumes from previous deployments, i'll use the configuration created when they were firstly created.
