### ISSUE TITLE
cache_dir is not writable error after installing Helm chart

### ISSUE THREAD

**Issue by adaniline** [bitnami/bitnami-docker-magento#94]
**Description**

Installed the latest chart version on Azure AKS K8S cluster, the megento pod does not finish initializing, /opt/bitnami/apache/logs/error_log file contains the following error.

Looking at /opt/bitnami/magento/htdocs dir, all folders are owned by root, but apache runs under a different user

```
Thu Oct 25 16:11:40.326547 2018] [core:notice] [pid 91] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
[Thu Oct 25 16:12:00.120964 2018] [:error] [pid 122] [client 10.240.0.4:44390] PHP Fatal error:  Uncaught Zend_Cache_Exception: cache_dir "/opt/bitnami/magento/htdocs/var/page_cache" is not writable in /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php:209\nStack trace:\n#0 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache/Backend/File.php(180): Zend_Cache::throwException('cache_dir "/opt...')\n#1 /opt/bitnami/magento/htdocs/vendor/colinmollenhour/cache-backend-file/File.php(87): Zend_Cache_Backend_File->setCacheDir('/opt/bitnami/ma...')\n#2 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_File->__construct(Array)\n#3 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true)\n#4 /opt/bitnami/magento/htdocs/vendor/magento/framework/App/Cache/Frontend/Factory.php(156): Zend_Cache::factory('Magento\\\\Framewo...', 'Cm_Cache_Backen...', Array, Array, true, true, true)\n#5 /opt/bitnami/magento/htdocs/vendor/magento/ in /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php on line 209
[Thu Oct 25 16:12:03.797121 2018] [:error] [pid 120] [client 10.240.0.4:44442] PHP Fatal error:  Uncaught Zend_Cache_Exception: cache_dir "/opt/bitnami/magento/htdocs/var/page_cache" is not writable in /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php:209\nStack trace:\n#0 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache/Backend/File.php(180): Zend_Cache::throwException('cache_dir "/opt...')\n#1 /opt/bitnami/magento/htdocs/vendor/colinmollenhour/cache-backend-file/File.php(87): Zend_Cache_Backend_File->setCacheDir('/opt/bitnami/ma...')\n#2 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_File->__construct(Array)\n#3 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true)\n#4 /opt/bitnami/magento/htdocs/vendor/magento/framework/App/Cache/Frontend/Factory.php(156): Zend_Cache::factory('Magento\\\\Framewo...', 'Cm_Cache_Backen...', Array, Array, true, true, true)\n#5 /opt/bitnami/magento/htdocs/vendor/magento/ in /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php on line 209
[Thu Oct 25 16:12:08.794705 2018] [:error] [pid 118] [client 10.240.0.4:44498] PHP Fatal error:  Uncaught Zend_Cache_Exception: cache_dir "/opt/bitnami/magento/htdocs/var/page_cache" is not writable in /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php:209\nStack trace:\n#0 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache/Backend/File.php(180): Zend_Cache::throwException('cache_dir "/opt...')\n#1 /opt/bitnami/magento/htdocs/vendor/colinmollenhour/cache-backend-file/File.php(87): Zend_Cache_Backend_File->setCacheDir('/opt/bitnami/ma...')\n#2 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_File->__construct(Array)\n#3 /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true)\n#4 /opt/bitnami/magento/htdocs/vendor/magento/framework/App/Cache/Frontend/Factory.php(156): Zend_Cache::factory('Magento\\\\Framewo...', 'Cm_Cache_Backen...', Array, Array, true, true, true)\n#5 /opt/bitnami/magento/htdocs/vendor/magento/ in /opt/bitnami/magento/htdocs/vendor/magento/zendframework1/library/Zend/Cache.php on line 209
```
**Steps to reproduce the issue:**

Install helm chart

**Describe the results you received:**

Magento pod does not initialize

**Describe the results you expected:**

Magento pod initializes

**Version**

K8S 1.10.7

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Azure AKS

**Comment by tompizmor** [comment]
Do you know if the Magento pod has been restarting before you see that error? 
Magento is an application with a huge amount of files and AKS is especially slow changing ownership and permissions so maybe the livenessChecks killed the Magento pod during the first initialization leaving the permissions in an inconsistent state. 

I would try to clean the environment and re-install the helm chart increasing the timeout values for liveness and readiness checks.

**Comment by adaniline** [comment]
livenessProbe delay was already set to 1000 seconds, should not take that long to change permissions, etc.
I will try with 6000 seconds delay, but it looks like it can be an issue with the user permissions in the container

**Comment by adaniline** [comment]
Thank you, @tompizmor, your suggestion worked - apparently the default 1000 sec delay was not enough for the initialization to finish, increasing it to 6000 helped - the app started!
Not sure if this project is the right place, but it would be nice to be able to customize the livenessProbe delay in the helm chart through values

**Comment by tompizmor** [comment]
@adaniline I'm glad it helped. 

I just sent this PR https://github.com/helm/charts/pull/8832 updating the magento chart to allow customizing the liveness and readiness probes in the helm chart.
